.TH EXPR 1
.SH NAME
expr \- Evaluate expressions
.SH SYNOPSIS
.B expr
[EXPRESSION]
.SH DESCRIPTION
This builtin concatenates all of its arguments into one arithmetic expression, evaluates it and returns its value. All of these functions/operators can also be found in other languages, such as C or Python.
.SS Precedence level 0
.RB ( , ) ;
.SS Precedence level 1 (ternary operator)
.RB ? , : ;
.SS Precedence level 2
.RB || , or ;
.SS Precedence level 3
.RB && , and ;
.SS Precedence level 4
.RB | ;
.SS Precedence level 5
.RB ^ ;
.SS Precedence level 6
.RB & ;
.SS Precedence level 7
.RB == , != ;
.SS Precedence level 8
.RB < , <= , > , >=
.SS Precedence level 9
.RB <=> ;
.SS Precedence level 10
.RB << , >> ;
.SS Precedence level 11
.RB + , - ;
.SS Precedence level 12
.RB * , / , // , % ;
.SS Precedence level 13: implicit
.SS Functions
.RB log10 , log2 , log , sqrt , sin , cos , ctg , tg , floor , ceil , abs;
.SS Other words
.RB nan , false , true ;
.SS Unary operators
.RB - , + , ~ .
.SH EXAMPLES
.EX
	echo [expr 1+2/(100**3+log(4))//2+sin 2+cos(floor(ceil(-8.7)))]
	echo [expr 1&&2||(1?2:0)+5&(3<<1)]
	echo [expr 1    +  2/ 3 +     4]
	# And so on and so forth...
.EE
