.TH LET 1
.SH NAME
let \- Use a lexical scoping block
.SH SYNOPSIS
.B let
<var list> <block>
.SH DESCRIPTION
The first argument of
.I let
must be a list representing the variables that will return to their original value after executing the second argument, which is a "code block".
.SH EXAMPLE
.EX
	set var1 = value
	set var2 = value
	let {var1 var2} {
		set var1 = a
		set var2 = b
	}
	#The original values were preserved!
	echo $var1 $var2
.EE
