.TH FN 1
.SH NAME
fn \- Define a new function
.SH SYNOPSIS
.B fn
<name> <block>
.SH DESCRIPTION
This builtin creates a new function with the specified name, that, when called, executes the statements provided by the second argument, replacing $argv(...) with its own arguments.
.PP
Alternatively, you can trap a signal by defining a function with the name of that signal. The artificial "signal" SIGEXIT occurs as Zrc is about to exit.
.SH EXAMPLES
.EX
	##############################################
	# A function to test if a number is a prime. #
	##############################################
	fn is_prime {
		if {$argv(1) < 2} {
			return 0
		} elsif {$argv(1) == 2) {
			return 1
		} elsif {$argv(1) % 2 == 0} {
			return 0
		} else {
			let {i ok} {
				set ok = 1
				for {set i = 3} {$i <= $argv(1)/2} {inc i} {
					if {$argv(1) % $i == 0} {
						set ok = 0
						set i = $argv(1)
					}
				}
				return $ok
			}
		}
	}

	##################
	# Trap SIGWINCH. #
	##################
	fn sigwinch {
		echo Window resized!
	}
.EE
