.TH READ 1
.SH NAME
read \- Read text from standard input
.SH SYNOPSIS
.BI "read [" "-d <delim>" | "-n <nchars>" "] [" "-p <prompt>" "] [" "<var1> <var2>..." ]
.SH DESCRIPTION
.I Read
is a command used to do various methods of text input. It can be used in conjunction with
.I stty
for more sophisticated reasons like formatted I/O functions, REPLs, and so on. This command can either read 'n' chars or a string separated by an IFS, and it can output to the stdout/set multiple variables' values. The utility may also display a prompt for the user if needed.
.SH OPTIONS
.TP
.B d <delim>
Choose which delimiter to use (IFS)
.TP
.B n <nchars>
Read n characters
.TP
.B d <prompt>
Display a prompt to the user
.SH EXAMPLES
.EX
	read str
	stty raw
	read -n 3
	stty cooked
	read txt -d ' '
.EE
