.TH RLIMIT 1
.SH NAME
rlimit - Increase/decrease stack size
.SH SYNOPSIS
.BI rlimit <n>
.SH DESCRIPTION
This command changes the interpreter's stack size to allow for deeper recursive functions. It accepts one argument, which represents (by default in bytes) the amount of memory to make the new stack size for Zrc. The builtin supports the prefixes K, M, G, T, P, E, Z, Y, B and g.
.SH EXAMPLES
.EX
	rlimit 256 # 256 bytes
	rlimit 1M  # 1 megabyte
	rlimit 2G  # 2 gigabytes
	#and so on...
.EE
